sble_backend/sble_backend/app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError, Length
from ..classes import User


class LoginForm(FlaskForm):
    email = StringField('Email:', validators=[DataRequired()])
    password = PasswordField('Password:', validators=[DataRequired()])
    remember_me = BooleanField('Remember me')
    submit = SubmitField('Log In')


class RegistrationForm(FlaskForm):
    email = StringField('Email:', validators=[DataRequired(), Email()])
    password = PasswordField('Password:', validators=[DataRequired()])
    password2 = PasswordField('Repeat Password:',
                              validators=[DataRequired(), EqualTo('password')])
    first_name = StringField('First Name:', validators=[DataRequired()])
    last_name = StringField('Last Name:', validators=[DataRequired()])
    submit = SubmitField('Register')

    def validate_email(self, email):
        user_exists = User.user_exists(email.data)
        if user_exists:
            raise ValidationError('Email already in use.')

sble_backend/sble_backend/app/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__)

from . import views, forms

sble_backend/sble_backend/app/user/views.py
from . import user
from .forms import LoginForm, RegistrationForm
from ..classes import User
from .. import login_manager
from flask import render_template, session, redirect, url_for, flash, request, g
from flask_login import current_user, login_user, logout_user, login_required


@user.route('/', methods=['GET', 'POST'])
def index():
    return render_template('index.html')


@user.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(first_name=form.first_name.data,
                        last_name=form.last_name.data,
                        email=form.email.data,
                        password=User.generate_password(form.password.data))
        new_user.create_user()
        flash("New user registered.")
        return redirect(url_for('user.login'))
    return render_template('register.html', title='Register', form=form)


@user.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user_found = User.find_user(email=form.email.data)
        if user_found and user_found.verify_password(form.password.data):
            login_user(user_found)
            # session['auth_token'] = user.generate_auth_token(expiration=3600)
            return redirect(request.args.get('next') or url_for('main.index'))
        flash('Wrong username or password')
        # if user_found is None or not user_found.verify_password(form.password.data):
        #     flash('invalid username or password')
        #     return redirect(url_for('user.login'))
        # login_user(user_found, remember=True)
        # return redirect(url_for('main.index'))

    return render_template('login.html', title='Log In', form=form)


@user.route('/logout')
@login_required
def logout():
    """
    Simply logout the currently logged in user.
    """
    logout_user()
    flash('Logged out')
    return redirect(url_for('main.index'))


@login_manager.user_loader
def load_user(user_id):
    if user_id is None:
        return redirect(url_for('user.login'))
    user_found = User.find_user(user_id=user_id)
    if user_found is not None:
        g.user = user_found
        return user_found
    else:
        return None

sble_backend/sble_backend/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    {% if title %}
    <title>{{ title }} - Application</title>
    {% else %}
    <title>Application</title>
    {% endif %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js">
    </script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>
<body>
    <div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 -pt-2 text-white min-vh-100>
                <a href="{{ url_for('main.index') }}" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <span class="fs-5 d-none d-sm-inline">SBLE</span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item"><a class="nav-link px-0 align-middle" href="{{ url_for('main.index') }}"><i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span></a></li>
                    {% if current_user.is_anonymous %}
                    <li class="nav-item"><a class="nav-link px-0 align-middle" href="{{ url_for('user.login') }}"><i class="fs-4 bi-box-arrow-in-left"></i> <span class="ms-1 d-none d-sm-inline">Login</span></a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link px-0 align-middle" href="{{ url_for('main.profile') }}"><i class="fs-4 bi-person"></i> <span class="ms-1 d-none d-sm-inline">Profile</span></a></li>
                    <li class="nav-item"><a class="nav-link px-0 align-middle" href="{{ url_for('main.search_data') }}"><i class="fs-4 bi-archive"></i> <span class="ms-1 d-none d-sm-inline">Search Data</span></a></li>
                    <li class="nav-item"><a class="nav-link px-0 align-middle" href="{{ url_for('main.leaderboard') }}"><i class="fs-4 bi-bar-chart"></i> <span class="ms-1 d-none d-sm-inline">Leaderboard</span></a></li>
                    <li class="nav-item"><a class="nav-link px-0 align-middle" href="{{ url_for('user.logout') }}"><i class="fs-4 bi-box-arrow-right"></i> <span class="ms-1 d-none d-sm-inline">Logout</span></a></li>
                    {% endif %}
                </ul>
                </div>
            </div>
            <div class="container-fuild m-3 w-auto">{% block content %}{% endblock %}</div>
        </div>
    </div>
</body>
</html>

sble_backend/sble_backend/app/templates/google_map.html
<!DOCTYPE html>
<!--
 @license
 Copyright 2019 Google LLC. All Rights Reserved.
 SPDX-License-Identifier: Apache-2.0
-->
<html>
  <head>
    <title>Add Map</title>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <script src="https://unpkg.com/@googlemaps/markerclusterer/dist/index.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='google_map.css') }}" />
    <script type="module" src="{{ url_for('static', filename='index.js') }}"></script>
  </head>
  <body>
    <h3>My Google Maps Demo</h3>
    <!--The div element for the map -->
    <div id="map"></div>

    <!--
     The `defer` attribute causes the callback to execute after the full HTML
     document has been parsed. For non-blocking uses, avoiding race conditions,
     and consistent behavior across browsers, consider loading using Promises
     with https://www.npmjs.com/package/@googlemaps/js-api-loader.
    -->
    <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCGkNEDMN4qR4Pe2b9cKXxB5yBawJWByIw&language=en&callback=initMap"
            defer
    ></script>
  </body>
</html>

sble_backend/sble_backend/app/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Home</h1>
<br>
<h3>Work in Progress</h3>
{% endblock %}

sble_backend/sble_backend/app/templates/leaderboard.html
{% extends "base.html" %}

{% block content %}
<h1 class="mb-3">Leaderboard</h1>
<div class="row">
    <table class="table table-striped table-bordered table-hover">
        <tr>
            <th>Email</th>
            <th>Total Minutes Spent Collecting Data</th>
        </tr>
        {% for key,val in entries.items() %}
        <tr>
            <td>{{ key }}</td>
            <td>{{ val.total_time_minutes }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

sble_backend/sble_backend/app/templates/login.html
{% extends "base.html" %}
{% block content %}
<h1>Log In</h1>
<form action="" method="post" novalidate>
    {{ form.hidden_tag() }}
    <div class="mb-3 mt-3 p-3 bg-secondary bg-opacity-25 rounded">
        <div>
            {{ form.email.label }}<br>
            {{ form.email(class_="form-control", size=32) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div>
            {{ form.password.label }}<br>
            {{ form.password(class_="form-control", size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit(class_="form-control") }}</p>
        <p>New User? <a href="{{ url_for('user.register') }}">Click to Register!</a></p>
    </div>
</form>
{% endblock %}

sble_backend/sble_backend/app/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1>Profile</h1>
<br>
{% if info %}
<h5 class="p-1">Username: <span class="border border-3 p-1 rounded">{{ info.username }}</span></h5>
<h5 class="p-1">Email: <span class="border border-3 p-1 rounded">{{ info.email }}</span></h5>
<h5 class="p-1">Name: <span class="border border-3 p-1 rounded">{{ info.firstname }} {{ info.lastname }}</span></h5>
<h5 class="p-1">Created on: <span class="border border-3 p-1 rounded">{{ info.created_on }}</span></h5>
{% endif %}
{% endblock %}

sble_backend/sble_backend/app/templates/register.html
{% extends "base.html" %}

{% block content %}
<h1>Register</h1>
<p><a href="{{ url_for('user.login') }}"><i class="fs-6 bi-box-arrow-left">  </i>Back to Login</a></p>
<form action="" method="post">
    {{ form.hidden_tag() }}
    <div class="d-grid gap-0 mb-3 mt-3 p-3 bg-secondary bg-opacity-25 rounded">
        <div>
            {{ form.email.label }}<br>
            {{ form.email(class_="form-control", size=32) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div>
            {{ form.password.label }}<br>
            {{ form.password(class_="form-control", size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div>
            {{ form.password2.label }}<br>
            {{ form.password2(class_="form-control", size=32) }}<br>
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div>
            {{ form.first_name.label }}<br>
            {{ form.first_name(class_="form-control", size=32) }}<br>
            {% for error in form.first_name.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div>
            {{ form.last_name.label }}<br>
            {{ form.last_name(class_="form-control", size=32) }}<br>
            {% for error in form.last_name.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <p">{{ form.submit(class_="form-control") }}</p>
    </div>
</form>
{% endblock %}

sble_backend/sble_backend/app/templates/search_data.html
{% extends "base.html" %}

{% block content %}
{% if filtered_data %}
<script>
    var data_object = {{ filtered_data|tojson|safe }};
</script>
{% endif %}
<script>
            function download_csv() {
                var data_csv = "timestamp,latitude,longitude,speed,speedAcc,vertical_acc,altitude,\
                course,courseAcc,heading,horizontal_acc,major,minor,rssi,rssi_accuracy\n";
                data_object.forEach(function(row) {
                    row.BLE.forEach(function(beacon) {
                        data_csv += row.timestamp + "," + row.GPS.latitude + ","
                        + row.GPS.longitude + "," + row.GPS.speed + "," + row.GPS.speedAcc
                        + "," + row.GPS.vertical_acc + "," + row.GPS.altitude + "," + row.GPS.course
                        + "," + row.GPS.courseAcc + "," + row.GPS.heading
                        + "," + row.GPS.horizontal_acc + "," + beacon.major + "," + beacon.minor
                        + "," + beacon.rssi + "," + beacon.accuracy;
                        data_csv += "\n";
                    });
                });

                var hiddenElement = document.createElement('a');
                hiddenElement.href = 'data:text/csv;charset=utf-8,' + encodeURI(data_csv);
                hiddenElement.target = '_blank';

                //provide the name for the CSV file to be downloaded
                hiddenElement.download = 'SBLE_data.csv';
                hiddenElement.click();
            }
</script>
{% if current_user.is_anonymous %}
<h1>Unauthorized access.</h1>
{% else %}
<h1>Search Data</h1>
{% if error %}
<p style="color:red">{{ error }}</p>
{% endif %}
<form action="" method="post">
    {{ form.hidden_tag() }}
    <div class="container-sm m-1 mb-2">
        <div class="row">
            <div class="mb-3 mt-3 p-3 bg-secondary bg-opacity-25 rounded" style="width:400px">
                <h4>Start Time:</h4>
                <div class="d-flex flex-row">
                    <div>
                        {{ form.start_month.label(class_='form-label') }}
                        {{ form.start_month(class_='form-select') }}
                    </div>
                    <div>
                        {{ form.start_day.label(class_="form-label") }}
                        {{ form.start_day(class_='form-select') }}
                    </div>
                    <div>
                        {{ form.start_year.label(class_="form-label") }}
                        {{ form.start_year(class_='form-select') }}
                    </div>
                </div>

                <div class="d-flex flex-row">
                    <div>
                        {{ form.start_hour.label(class_='form-label') }}
                        {{ form.start_hour(class_='form-select') }}
                    </div>
                    <div>
                        {{ form.start_minute.label(class_="form-label") }}
                        {{ form.start_minute(class_='form-select') }}
                    </div>
                    <div>
                        {{ form.start_period.label(class_="form-label") }}
                        {{ form.start_period(class_='form-select') }}
                    </div>
                </div><br>

                <h4>End Time:</h4>
                <div class="d-flex flex-row">
                    <div>
                        {{ form.end_month.label(class_='form-label') }}
                        {{ form.end_month(class_='form-select') }}
                    </div>
                    <div>
                        {{ form.end_day.label(class_="form-label") }}
                        {{ form.end_day(class_='form-select') }}
                    </div>
                    <div>
                        {{ form.end_year.label(class_="form-label") }}
                        {{ form.end_year(class_='form-select') }}
                    </div>
                </div>

                <div class="d-flex flex-row">
                    <div>
                        {{ form.end_hour.label(class_='form-label') }}
                        {{ form.end_hour(class_='form-select') }}
                    </div>
                    <div>
                        {{ form.end_minute.label(class_="form-label") }}
                        {{ form.end_minute(class_='form-select') }}
                    </div>
                    <div>
                        {{ form.end_period.label(class_="form-label") }}
                        {{ form.end_period(class_='form-select') }}
                    </div>
                </div>

                <div>
                    {{ form.beacon_major.label }}<br>
                    {{ form.beacon_major(class_="form-control", size=32) }}<br>
                    {% for error in form.beacon_major.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </div>

                <h4>Bounding Box:</h4>
                <div>
                    {{ form.bbox_botleft.label }}<br>
                    {{ form.bbox_botleft(class_="form-control", size=32) }}<br>
                    {% for error in form.bbox_botleft.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </div>
                <div>
                    {{ form.bbox_topright.label }}<br>
                    {{ form.bbox_topright(class_="form-control", size=32) }}<br>
                    {% for error in form.bbox_topright.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </div>
            <p>{{ form.submit(class_="form-control", ) }}</p>
            <button class="btn btn-primary" onclick="download_csv()">Download as CSV</button>
            </div>
        </div>
    </div>
</form>
<table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
        <th>Time Stamp</th>
        <th>GPS</th>
        <th>BLE</th>
    </tr>
    </thead>
    <tbody>
        {% for data in filtered_data %}
        <tr>
            <td>{{ data.timestamp }}</td>
            <td>{{ data.GPS }}</td>
            <td>{{ data.BLE }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
{% endblock %}

sble_backend/sble_backend/app/templates/user.html
{#{% extends 'base.html' %}#}
{##}
{#{% block content %}#}
{#    <h1>User: {{ user_found.first_name }}</h1>#}
{#    <hr>#}
{#    {% for post in posts %}#}
{#    <p>#}
{#        {{ post.author.username }} says: <b>{{ post.body }}</b>#}
{#    </p>#}
{#    {% endfor %}#}
{#{% endblock %}#}